sudo: required

services:
  - docker

script:
  - docker build -t docker-nodejs-python .
  - docker run docker-nodejs-python /bin/sh -c "npm -v && node -v && python --version && phantomjs --version && casperjs --version"
